---
- name: apt packages installed
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - gcc
    - libpq-dev
    - python-dev
    - libmemcached-dev
    - memcached

- name: pip packages installed
  become: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualenv

- name: app deps installed
  pip:
    requirements: "{{ repo_dir }}/requirements.txt"
    virtualenv: "{{ venv_dir }}"
    state: present

- name: test deps installed
  pip:
    name: "{{ item }}"
    virtualenv: "{{ venv_dir }}"
    state: present
  with_items:
    - django-test-without-migrations
    - django-slowtests

- name: app settings file created
  copy:
    src: "{{ app_dir }}/settings_local_example.py"
    dest: "{{ app_dir }}/settings_local.py"

- name: necessary directories created
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "~/logs"
    - "~/.the-tale"
